### ISSUE TITLE
Add version without TypeScript support

### ISSUE THREAD

**Issue by thorsten** [TobiasWalle/rush#1]
Please add a version without the requirement of TypeScript, as almost no one uses React with TypeScript. :)

**Comment by TobiasWalle** [comment]
Hello Thorsten,

Thank you for this recommendation, but at the moment I really want to focus on providing the best possible experience with typescript. Even if the majority of react developers is currently using javascript, I think react and redux in combination with typescript provides a lot of amazing advantages expecially then creating bigger projects in a team.

There are a lot of great generators for react with javascript available like [create-react-app](https://github.com/facebookincubator/create-react-app). But I really recommend to give react with typescript a try ;)

Regards
Tobias
